services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops_n2_app
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=0.0.0.0
      - PORT=5000
    volumes:
      - .:/app
    restart: unless-stopped
